nsqio/pynsq

- setup.py
Let's pin installs to not exceed the last compatible version of Tornado until #115 is resolved.
> Pin to tornado<4 until compatible

- nsq/async.py
I suspect this was a typo. The "CONNECT" event was being triggered when the socket was closed. It should instead be the "CLOSE" event.
Regards.
> Triggering the correct "CLOSE" event when the socket is closed

- nsq/reader.py
- tests/test_reader.py
Fixes bug #122.
Add a call to close to the message test to exercise the code. Verified
the test fails without the fix.
> Fix exception in Reader.close() when query_periodic is None

- .travis.yml
- nsq/async.py
- nsq/deflate_socket.py
- nsq/snappy_socket.py
- setup.py
The Snappy & Deflate socket send routines need to return the number of
bytes they sent.
If the underlying socket.send() fails then we're toast.
Update travis to test with tornado 4.0 & 4.1, and update setup.py.
> Reenable tornado 4

- nsq/async.py
> reader: add msg_timeout IDENTIFY option

- nsq/async.py
If read_bytes is called when the connection is closed and there is nothing in the buffer, an iostream.StreamClosedError is thrown. This is caught in _read_size by the generic exception catcher but uncaught in _start_read.
This can be checked for beforehand by doing checking "if self.stream.closed()" before calling self.stream.read_bytes(). In this case, no buffered data would get processed, but processing the buffered data seems to be the intended behavior of the stream. Of course, processing the buffered data will eventually result in the error log message about not being able to send the FIN.
> asyncconn: catch connection closed error on read_bytes

- .travis.yml
- nsq/reader.py
- travis_test.sh
Due to the "don't decrement rdy" change to nsqd behavior (https://github.com/bitly/nsq/pull/404), the current effect of `disabled()` returning `True` in `nsq.Reader`, of not sending any ready count (never calling `_send_rdy()`), fails to reduce the ready count to zero on the nsqd side.
> nsq.Reader.disabled() no longer effective

- nsq/__init__.py
This adds in a SIGINT handler, to ensure that ctrl-c, is caught in the
nsq.run() loop.
@mreiferson this is a follow up from our conversation, let me know if there's anything else you'd like to see documented and/or anything else that needs to be done to get this pushed through.
> Add SIGINT handler

- nsq/snappy_socket.py
I'm not sure how to reproduce this issue. I am using snappy for writing to nsqd but not when reading, maybe that is what's causing this issue.
WARNING:tornado.general:error on read
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 644, in _handle_read
pos = self._read_to_buffer_loop()
File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 614, in _read_to_buffer_loop
if self._read_to_buffer() == 0:
File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 726, in _read_to_buffer
chunk = self.read_from_fd()
File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 1005, in read_from_fd
chunk = self.socket.recv(self.read_chunk_size)
File …
> Snappy socket undeclared variable

- nsq/async.py
This fixes the hardcoding of max_rdy_count to 2500 to the value received from the IDENTIFY request. It defaults back to 2500 for older nsq versions. See #131
> set max_rdy_count to value received from IDENTIFY response. see #131

- tests/test_async.py
In order to get the tests passing with recent versions of mock, we need
to omit the `autospec=True` parameter for `socket.socket` mocks.
See:
https://github.com/testing-cabal/mock/issues/323
> Work around a bug in mock's autospec support

- travis_test.sh
Currently, the tests aren't running on Travis, as we `cd snappy` and never `cd ..`, meaning that py.test discovery doesn't find any tests to run.
This commit tidies up the `travis_test.sh` script a little, improves the output on Travis by folding non-test-related output, and ensures that we're in the correct directory when we run py.test.
> Tidy up travis_test.sh and ensure tests actually run

- .travis.yml
- nsq/_compat.py
- nsq/async.py
- nsq/protocol.py
- nsq/reader.py
- nsq/sync.py
- nsq/writer.py
- tests/test_async.py
- tests/test_backoff.py
- tests/test_command.py
- tests/test_reader.py
- tests/test_sync.py
I'm super keen to get a version of `pynsq` working on Python 3. There appear to have been a couple of valiant attempts to get this working in the past, including #88, #102, and most recently #127. None of these have been merged, so here's another attempt to get this working, which tries to achieve the following:
- Each set of changes has been made in its own commit, with an explanation of what the change is and why it's needed for Python 3 compatibility.
- I've made sure that the concerns previously raised [[1](https://github.com/nsqio/pynsq/pull/102#discussion_r20363807), [2](https://github.com/nsqio/pynsq/pull/127#discussion_r32329639)] around ensuring that message bodies are bytestrings, not text, have been addressed. (*N.B.* The code previously didn't check individual bodies in `mpub` …
> Python 3 compatibility, round two

- nsq/_compat.py
- nsq/async.py
- nsq/protocol.py
- nsq/sync.py
- tests/test_async.py
- tests/test_command.py
- tests/test_sync.py
From the python docs: 
> Creating a Struct object once and calling its methods is more efficient than calling the struct functions with the same format since the format string only needs to be compiled once.
> Reuse struct objects

- nsq/backoff_timer.py
my version of #155 
performance tested with @virtuald's [rawperf.py](https://gist.github.com/virtuald/d7416e06d0d348af30aa1425fb67a5b6) on a plugged-in 2013 macbook pro retina 13"
* master: about 16s
* optim_backofftimer: about 12s
Maybe a refactor - to not call these methods so much - is what the library really needs, but this was a fun easy exercise :grin:
> reader: optimize BackoffTimer using float

- nsq/async.py
- tests/test_async.py
The first one is pretty self-explanatory (maybe needs another PR?) -- only call `time.time()` once, the extra function overhead (despite how small it is) isn't necessary.
The second one we can debate, in the reader it now immediately calls _start_read() instead of going through the IOLoop to call it. This results in a ~1s improvement in my [rawperf script](https://gist.github.com/virtuald/d7416e06d0d348af30aa1425fb67a5b6). I think I understand why it was done this way originally -- presumably don't want to starve the IOLoop if messages just happen to come in at the perfect rate where the socket buffer can keep feeding messages... since the read functions will call each other continuously in a loop without yielding to the IOLoop.
But... I wonder if that can actually happen?
If it can …
> Minor performance tweaks

- nsq/reader.py
Tornado's HTTPResponse body is of type bytes in Python3 and json.loads cannot be performed. 
Execution of:
```
import tornado.ioloop
import nsq
def handler(message):
print(message)
return True
r = nsq.Reader(message_handler=handler,
lookupd_http_addresses=['nsqlookupd:4161'],
topic='test', channel='test', lookupd_poll_interval=15)
nsq.run()
tornado.ioloop.IOLoop.current().start()
```
Results with:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/tornado/ioloop.py", line 604, in _run_callback
ret = callback()
File "/usr/local/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.5/site-packages/nsq/reader.py", line 597, in _finish_query_lookupd
lookup_data = …
```
> reader: python3 type error in nsqlookupd response parsing

- nsq/protocol.py
% formatting is availble since python 3.5
see: http://legacy.python.org/dev/peps/pep-0461/
> fix protocol.SendError in python 3.4

- nsq/reader.py
pynsq was not yet making 1.0 compatible queries to lookupd, so this code breaks due to the deprication of the old format in nsqio/nsq#367. This updates to pass the right header to make forwards compatible queries.
> 1.0 compatible lookupd queries

- nsq/async.py
- nsq/version.py
- setup.py
- tests/test_sync.py
This adds support for new IDENTIFY fields as support for the old fields was removed from nsqd in nsqio/nsq#367
> IDENTIFY: send 1.0 compatible client_id and hostname fields

- .gitignore
- nsq/async.py
According to the NSQ protocol, consumers have to send `FIN`s for every
message they receive, which makes them extremely slow with low `max_in_flight`
values due to TCP buffering.
Adding TCP_NODELAY option on `async.AsyncConn`'s sockets makes `nsq.Reader`
substantially faster. My tests show increase from ~50 to ~4.5K messages per
second on localhost with `max_in_flight = 1`.
----
NODELAY will be enabled by default. It may be disabled by passing `nodelay=False` to `Reader`/`Writer` ctor's kwargs.
> Use TCP_NODELAY for improved latency

- nsq/async.py
- nsq/reader.py
- tests/test_backoff.py
- tests/test_reader.py
This brings reader behavior into agreement with nsqd behavior (after nsqio/nsq#404) and removes an opportunity for max_in_flight violations (#177).
This [block](https://github.com/nsqio/pynsq/blob/master/nsq/reader.py#L322-L332) was removed because it's redundant given `_redistributed_rdy()` and it's easier to maintain invariants without it.
@mreiferson
> reader:  don't decrement total_rdy on message receipt

- nsq/message.py
Before this fix zero delay was not correctly converted and time_ms took its default value -1.
> Fix converting zero delay to time_ms in Message.requeue()

- nsq/reader.py
- tests/reader_unit_test_helpers.py
- tests/test_backoff.py
- tests/test_rdy.py
Fixes #182.
Previously, a connection's `rdy` attribute was decremented on message receipt; when it [dipped low enough](https://github.com/nsqio/pynsq/blob/07a75bd5e99ade9d1f6a13593d5bfa17e67c17f4/nsq/reader.py#L361) the connection would send a new `RDY` count of `_connection_max_in_flight()`.  One consequence of this was that, when `_connection_max_in_flight()` changed (because either the connection count or the reader's `max_in_flight` attribute changed), each connection would eventually update to the new value.
The reader's `total_rdy` attribute was also decremented on message receipt.  This guaranteed (under the assumption that some connection was receiving messages), that `total_rdy` would drop below `max_in_flight`, freeing up space for a new connection to send an initial `RDY` count …
> reader: make sure RDY is updated when connection count changes

- nsq/async.py
pynsq now only supports override `user_agent` and not supporting override `hostname`.
In cases we run a consumer in a container, the `hostname` shell command will return a docker id which is a random string. When we check the client info in nsqadmin we can not get any useful info about the host name where consumer running.
With enable override `hostname`, we can set the consumer, running in a container, `hostname` to the host name where the container is running which is helpful when we want to determine which host to get the consumers.
/cc @mreiferson @alpaker
> add support for custom hostname

- nsq/_compat.py
- nsq/reader.py
- nsq/writer.py
Both `cgi.parse_qs` and `inspect.getargspec` will be deprecated. This pull will replace these with `urllib.parse.parse_qs` and `inspect.signature` respectively if available.
> Deprecation warnings

- nsq/_compat.py
- nsq/reader.py
- nsq/writer.py
As promised, a fix for dealing with `inspect.getargspec` being deprecated and `inspect.signature`'s return type not being compatible. This introduces a separate method `func_args` for deriving the method's signature arguments which wraps either `inspect.signature` or `inspect.getargspec` depending on which is available.
> Add separate method to derive function signature args

- .travis.yml
- nsq/deflate_socket.py
- nsq/snappy_socket.py
This updates pynsq to be tested on tornado 4.5, and adds python 3.6 to the test matrix.
This also drops support for tornado 3.2, and adds test coverage for 4.1.x
Releated to #191 #194
> Update Tornado Compatability Matrix

- nsq/reader.py
> fix typo "pool" in `Reader` doc

- docs/index.rst
Hi, I just updated the `NSQ Protocol` url because the old one return 404 status code.
> Update the `NSQ Protocol` url

- setup.py
On March 5th, 2018, version 5.0 of tornado was released http://www.tornadoweb.org/en/stable/releases/v5.0.0.html.
This major version release is currently incompatible with pynsq as some underlying API's have changed.
One such change is where pynsq relies on `tornado.simple_httpclient._default_ca_certs` which no longer exists in v5.0:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/nsq/async.py", line 31, in <module>
from tornado.simple_httpclient import _default_ca_certs as default_ca_certs
ImportError: cannot import name '_default_ca_certs'
```
There are likely other incompatible changes yet to be determined.  For now, it'd be helpful if `pynsq` specified it's compatible versions.
cc/ @mreiferson
> pynsq: specify tornado version less than 5.0

- nsq/deflate_socket.py
- nsq/snappy_socket.py
- fixed handling messages from closed connection in DeflateSocket/SnappySocket recv()
- made DeflateSocket//SnappySocket recv() behaves as standart socket when connection is closed
If connection to nsqd is closed then reading from socket returns empty result and socket should be closed, otherwise it will lead to constant attempt to read from it, and to high cpu load.
> fix high CPU load in DeflateSocket on nsqd disconnection

- .travis.yml
- nsq/async.py
- nsq/protocol.py
- nsq/reader.py
- setup.py
- tests/test_command.py
- tests/test_sync.py
- travis_test.sh
I think we can reduce the overall test matrix by not testing everything with everything, but rather being a bit more judicious.
Includes small bumps to to snappy and tornado 4.5.z, removes dependency on simplejson.
Adds experimental python3.7 support, probably a good idea to defer this bit to a follow-up PR ...
> tests: update Travis-CI test matrix / lib versions

- docs/conf.py
- examples/all_identify_options.py
- nsq/__init__.py
- nsq/async.py
- nsq/conn.py
- nsq/reader.py
- nsq/writer.py
- tests/test_reader.py
- tox.ini
- travis_test.sh
I'd be happy to make stylistic changes to the bits I had to tweak to avoid warnings.
> run flake8 on Travis-CI, make flake8 clean

- nsq/conn.py
- tests/test_reader.py
The root issue is that on python3 there are conflicting type assertions for auth_secret:
```python
class AsyncConn(...):
def __init__(...):
assert isinstance(auth_secret, string_types + (None.__class__,))
...
def _on_response_continue(...):
self.send(protocol.auth(self.auth_secret))
def auth(data):
return _command(AUTH, data)
def _command(cmd, body, *params):
assert isinstance(body, bytes_types), 'body must be a bytestring'
```
in #202, @ericb proposed just changing the initial type assertion to allow `bytes_types` instead of `string_types`. I'm fine with that, but I think it might be more "natural" to allow a string for `auth_secret` as well, so I've come up with my own variation using `to_bytes`.
(pushing just the test first to demonstrate failures, then the fix ...)
> fix auth_secret identify option on python3

- setup.py
- tests/test_basic.py
- tests/test_command.py
- travis_test.sh
to avoid deprecation warnings for addcall() from py.test
we need pytest>=3.3.1 for a bugfix for parameters with null bytes
(but travis-ci seems to have pytest-3.3.0 installed ... sometimes??)
> tests: switch from Metafunc.addcall() to mark.parametrize()

- nsq/conn.py
Removed the hard coded TLSv1 version in `ssl.wrap_socket`. 
TLS options for a reader can be set with `tls_options`, however the ssl_version is already explicitly set which yields the following error when trying to set a different version:
` TypeError: wrap_socket() got multiple values for keyword argument 'ssl_version'`
This prevents me from using pynsq with `-tls-min-version=tls1.2` set on my nsqds. Removing the hard coded version allows setting this value as/if needed. Running without the hardcoded value, `nsq.Reader` with `tls_v1=True` and omitting `tls_options` correctly uses the min tls version set by nsqd.
> Remove hardcoded tlsv1 version in ssl.wrap_socket

- examples/nsq_to_nsq.py
- nsq/legacy_reader.py
- nsq/reader.py
- nsq/writer.py
- tests/test_command.py
- travis_test.sh
A new version of flake8 was recently released, and new warnings
caused the test-suite to fail. This explicitly installs 3.6.0 so
after the latest warnings are fixed, this won't happen again
unexpectedly.
Also re-arrange travis_test.sh a bit.
> tests: explicitly install flake8 3.6.0 on travis-ci

- .travis.yml
replace nsq 1.1.0-rc1 with 1.1.0 (final)
use new-ish travis-ci "xenial" base for all
~~try adding pypy to the test matrix~~ pypy has some compatibility issue with the snappy module, we would have to make the tests optionally exclude any dependence on the snappy compression (do I forget this and find out again every time ...)
> tests: travis-ci test matrix updates

- nsq/reader.py
Naively enforcing that invariant in `_send_rdy()` prevents us from correctly updating each conn's `rdy` after reducing `max_in_flight`.  Additionally, there's no need for this check in `_send_rdy()`, as all callers have logic that's supposed to determine an appropriate rdy value.
> reader: in send_rdy(), don't enforce total_rdy <= max_in_flight

- .travis.yml
- nsq/client.py
- nsq/conn.py
- nsq/deflate_socket.py
- nsq/reader.py
- nsq/snappy_socket.py
- nsq/version.py
- setup.py
- tests/reader_unit_test_helpers.py
- tests/test_async.py
- tests/test_backoff.py
- tests/test_rdy.py
- tests/test_reader.py
- tests/test_writer.py
- travis_test.sh
addresses #185 and #203 
~~still adapting tests ... they passed in a mocked io_loop so it's a pretty big change if they can't do that~~ adapted
> tornado 5.x support

- nsq/message.py
refer to https://stackoverflow.com/a/5901825/334999. 
2.x also has a type bytes which is just an alias to str, so "bytes" is a proper type for message.body attribute.
> modify message body type comment, string => bytes

- nsq/conn.py
- tests/test_backoff.py
This PR will reduct duplicate rdy update requests.
> reduce duplicate rdy update requests

- .github/workflows/main.yml
- docs/requirements.txt
- nsq/__init__.py
- nsq/conn.py
- nsq/reader.py
- nsq/writer.py
- setup.py
- tests/reader_unit_test_helpers.py
- tests/test_async.py
- tests/test_reader.py
- tests/test_writer.py
~~needs a couple tests for the new coroutine support~~ (done)
needs pydoc updates
could refactor a bit to use coroutines in one or two more places internally ... tests with mocks make this annoying
> support tornado-6.x, support coroutine message_handler

- nsq/backoff_timer.py
- nsq/protocol.py
- nsq/writer.py
There are small typos in:
- nsq/backoff_timer.py
- nsq/protocol.py
- nsq/writer.py
Fixes:
- Should read `successful` rather than `successfull`.
- Should read `publishing` rather than `publshing`.
- Should read `commands` rather than `commmands`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos
